config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  get 'rooms/index'

  get 'chat_messages/index'

  get 'users/index'

  get 'users/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'home/index'

  get 'home/show'
  get 'home/friend'
  

  root to: "home#index"
  resources :users do
    member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :tickets, shallow: true do
     resources :reservations
     resources :reviews
  end

resources :charges

get '/connect/oauth' => 'stripe#oauth', as: 'stripe_oauth'
get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'
get "users/:id/useside" => "users#useside", as: 'useside'
get "users/:id/lend" => "users#lend",  as: 'lend'

  
end

app/models/user.rb
class User < ApplicationRecord
	 include Gravtastic
        gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable



  
  
   has_many :ticket, dependent: :destroy
   has_many :reservation, dependent: :destroy
   has_many :review
   has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
   has_many :followings, through: :following_relationships
   has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
   has_many :followers, through: :follower_relationships




   def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def feed
   following_ids = "SELECT following_id FROM relationships
                     WHERE follower_id = :user_id"
    Ticket.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

    def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.username = auth.info.name
    # //user.image = auth.info.image // 画像ようにつかう
    #   # assuming the user model has a name
   # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
  end
  end

  def connected?
    !stripe_user_id.nil?
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	 @users = User.all
  end

  def show
  	@user = User.find(params[:id])
  	@ticket = @user.ticket.all
  end

  def useside
    @user = User.find(params[:id])
  	@reservation = current_user.reservation.all
  end

  def lend
    @user = User.find(params[:id])
    @ticket = current_user.ticket.all
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end




  



end

app/helpers/users_helper.rb
module UsersHelper
   def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

   def current_user?(user)
     user == current_user
  end
end

app/views/users/_follow.html.erb
 <%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
 <% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>  

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
 
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/lend.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-10 col-md-offset-1">

			<table class="table table-striped">
			<tr>
			 <th>タイムシェアする名前</th>
			 <th>タイムシェアをお願いする人の名前</th>
			 <th>予約日時</th>
			 <th>状況</th>
			 <th>状況変更</th>
				


			</tr>
			<% @ticket.each do |ticket| %>
					<% ticket.reservation.each do |reservation| %>
					
					<tr>
					<td><%= ticket.title %></td>
					<td><%= link_to reservation.user.username,user_path(reservation.user_id) %></td>
					<td><%= reservation.startdate.strftime('%Y年%m月%d日 %H:%M') %></td>
					<td><%= reservation.approval %></td>
					<td><%= link_to  ticket.title, reservation_path(reservation)%></td>
					</tr>
					
					
					

					<% end %>
					<% end %>
					
			</table>
</div>
</div>
</div>

app/views/users/show.html.erb
            <div class="col-sm-12">
             <div class="container">
               <div class="row">
             
                <div class="jumbotron" id="usershowjjumbotron">
                 
                  　<!-- 背景の色// -->
                    <h1 class="display-3">  </h1>
                    <p class="lead">　
                     <p class="text-center">

                    　<%= image_tag current_user.gravatar_url %><%= @user.username %>
                    	</p>
                    </p>
                    <hr class="my-4">
                    <div id="userselfintroduction1">
                    自己紹介文<br>
                     <%= @user.Selfintroduction %>
                    </div>

                    　　　<%= render 'follow_form' %>
　　　                   <%= render 'stats' %>
                    
                    </p>
                    
                  </div>　
             </div>
            </div>
          </div>
            <div class="col-sm-12">
             <div id="usershowall">このユーザーの全てのタイムシェア　</div>
           
             <% @ticket.each do |ticket| %>
           
             

                  

                 
             　
               <div class="col-md-4">
                <div id="usershowsqaure">
                
               
                 <p class="text-center">
                     
               
               
                <table class="table table-striped">
                        <tbody>
                            <tr>
                                <th scope="row">種類</div></th>
                                <td> <%= ticket.sort %></td>
                            </tr>
                            <tr>
                                <th scope="row">タイムシェアの題名</th>
                                <td><%= ticket.timeuse %>
                                    
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">使える時間</th>
                                <td>
                                    <%= ticket.timeuse %>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">価格</th>
                                <td><%= ticket.price %>
                                    
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">手段</th>
                                <td><%= ticket.area %>
                                    
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">内容</th>
                                <td><%= ticket.content %>
                                    
                                </td>
                            </tr>
                        </tbody>
                    </table>

                     </p>

               

                </div>
               
                </div>
              

                  
                 
                      
                   
   
                 
                 
                  <% end %>
                  
                  

                     
          　</div>          
            <div class="col-sm-12">
            
                 <h1> レビユーをする</h1>
            </div>
       
 

    

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
<table>
<tr>
  <td><%= image_tag user.gravatar_url %></td>
  <td> <%= user.username %> </td>
  <td><%= link_to 'プロフィール', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/show_follower.html.erb
 <% @user.followers.each do |user| %>
<table>
<tr>
  <td>  <%= user.username %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/useside.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-10 col-md-offset-1">
<h1>あなたが予約した一覧</h1>
 


<table class="table table-striped">
  <tr>
    <th>名前</th>
    <th>予約日時</th>
    <th>承認状況</th>
    <th>リンク</th>
    <th>レビュー評価</th>
  </tr>


  
   <% @reservation.each do |reservation| %>


      <td><%= reservation.ticket.title %></td>
      <td><%= reservation.startdate.strftime('%Y年%m月%d日 %H:%M') %></td>
      <td><%= reservation.approval %></td>
     
      <td><%= link_to "リンク", ticket_path(reservation.ticket_id) %></td>
      <td><%= link_to reservation.ticket.title + "のレビュー評価を書く",  new_ticket_review_path(reservation.ticket_id) %></td>
    </tr>

    <% end %>
   
</table>
</div>
</div>
</div>