config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  get 'rooms/index'

  get 'chat_messages/index'

  get 'users/index'

  get 'users/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'home/index'

  get 'home/show'
  get 'home/friend'
  

  root to: "home#index"
  resources :users do
    member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :tickets, shallow: true do
     resources :reservations
     resources :reviews
  end

resources :charges

get '/connect/oauth' => 'stripe#oauth', as: 'stripe_oauth'
get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'
get "users/:id/useside" => "users#useside", as: 'useside'
get "users/:id/lend" => "users#lend",  as: 'lend'

  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!, only: :show
  def index
  end

  def show
  	@ticket = Ticket.where.not(user_id: current_user).order("RANDOM()").limit(6)
  	 
  end

  def friend
      
      @feed_items = current_user.feed.paginate(page: params[:page])
    
  	
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/friend.html.erb
<div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
</div>

app/views/home/index.html.erb
<div class="topimage">
	<%= image_tag("toppage.jpg",:width => "100%",:height => "500") %>
</div>
<div class="container-fluid">
		 
	<div class="row">
		<div class="col-md-4 col-sm-4 topguide text-center">
		 <div class="glyphicon glyphicon-calendar" style="font-size:35px"><br>
		  <div class="topguidemozi" >
		 	相手と自分な時間に調整することができます
		   </div>
		 </div>
			
		</div>
		<div class="col-md-4 col-sm-4 topguide text-center">
		 <div class="glyphicon glyphicon-circle-arrow-up" style="font-size:35px"><br>
		 <div class="topguidemozi" >
		  相手の力を借りて新しい知識を建てることができます
		  </div>
		  </div>
		 </div> 



		<div class="col-md-4 col-sm-4 topguide text-center">
		<div class="glyphicon glyphicon-comment" style="font-size:35px"><br>
		<div class="topguidemozi" >
			気軽に教えたり、教えってもらったりできます。
			</div>
		</div>
		</div>
	</div>
</div>
<footer>
   <div class="footdesign">
    <div clsss="text-center", id="footmozi">
    タイムシェア
    </div>
  </footer>

   <ul class="list-group">
    <li class="list-group-item" id="stripe-oauth">
      <!-- Call stripe controller's oauth action -->
      <p>下のボタンをクリックした後、情報を入力することで銀行口座を登録できます。</p>
      <%= link_to stripe_oauth_path do %>
        <%= image_tag "blue-on-light.png"%>    
      <% end %>
    </li>
  </ul> 

 

app/views/home/show.html.erb
<div class="col-sm-12">
             
          </div>
            <div class="col-sm-12">
             <div id="usershowall">ランダムおすすめ　<br>
             あなた以外のタイムシェアチェットをランダムに６個まで表示する
             </div>
           
             <% @ticket.each do |ticket| %>
           
             

                  

                 
             　
               <div class="col-md-4">
                <div id="usershowsqaure">
                
               
                 <p class="text-center">
                     
               
               
                <table class="table table-striped">
                        <tbody>

                        <tr>
                                <th scope="row">種類</div></th>
                                <td> <%= ticket.user_id %></td>
                            </tr>
                         
                                
                    
                            <tr>
                                <th scope="row">種類</div></th>
                                <td> <%= ticket.sort %></td>
                            </tr>
                            <tr>
                                <th scope="row">タイムシェアの題名</th>
                                <td><%= ticket.timeuse %>
                                    
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">使える時間</th>
                                <td>
                                    <%= ticket.timeuse %>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">価格</th>
                                <td><%= ticket.price %>
                                    
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">手段</th>
                                <td><%= ticket.area %>
                                    
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">内容</th>
                                <td><%= ticket.content %>
                                    
                                </td>
                            </tr>
                               <th scope="row">リンク</th>
                                <td><%= link_to  "このタイムシェアのリンクする", ticket_path(ticket) %>
                                    
                                </td>
                            </tr>
                        </tbody>
                    </table>

                     </p>

               

                </div>
               
                </div>
              

                  
                 
                      
                   
   
                 
                 
                  <% end %>
                  
                  

                     
          　</div>          
            
    